use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};

// Stage 0-external experimental product integration. The frozen Stage 0 ABI is
// unchanged; this version governs only the consent-gated product CodeAgent task.
pub const TASK_SCHEMA_VERSION: &str = "vibapp.cloud-codeagent-task.experimental-v3";
const TASK_SCHEMA_SNAPSHOT_SHA256: &str =
    "fb2a49186349aa4542ab6bab9440fe2e5c48a9d7cc86085449a71e20ecdb73ab";
const PROVIDER_REQUEST_VERSION: &str = "vibapp.cloud-codeagent-provider-request.experimental-v7";
const POLICY_VERSION: &str = "vibapp.cloud-codeagent-policy.experimental-v7";
const CARGO_SCAFFOLD_POLICY_VERSION: &str = "vibapp.cloud-codeagent-cargo-scaffold.experimental-v1";
const CONTRACT_DIGEST_SHA256: &str =
    "ec94f06652886cf9eea0aba8afc028165b135b91103faccf62a2ccc6828d3c38";
const CODEX_INSTRUCTIONS_DIGEST_SHA256: &str =
    "49fe02f64ab181e3c9a1ce22729bd3ec1309a5afa7b8a4b39e14391d95650536";
const OTHER_PROVIDER_INSTRUCTIONS_DIGEST_SHA256: &str =
    "406373f344973f6eef09a2973bda945594fdb7a14cb5df5ac51fe5b78d216d2a";
const OPENCODE_INSTRUCTIONS: &str =
    include_str!("../../../cloud-agent/starter/opencode_instructions.txt");
const CODEX_UI_INSTRUCTIONS: &str =
    include_str!("../../../cloud-agent/starter/codex_instructions.txt");
const OPENCODE_UI_SUPPORT: &[u8] =
    include_bytes!("../../../cloud-agent/starter/vibapp_support.rs");
const OPENCODE_UI_GUIDE: &[u8] = include_bytes!("../../../cloud-agent/starter/README.md");
const UI_UX_SKILL: &[u8] = include_bytes!("../../../cloud-agent/skills/vibapp-ui-ux/SKILL.md");
const CLOUD_AGENT_POLICY_SOURCE: &str = include_str!("../../../cloud-agent/cloud_agent.py");
const DISCLOSED_DATA_CLASSES: &[&str] = &[
    "need",
    "package-intent",
    "target-contract",
    "execution-limits",
    "generation-policy",
    "authoritative-contract",
    "provider-execution-identity",
];

fn canonicalize(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut keys = map.keys().collect::<Vec<_>>();
            keys.sort_unstable();
            let mut canonical = Map::new();
            for key in keys {
                canonical.insert(key.clone(), canonicalize(&map[key]));
            }
            Value::Object(canonical)
        }
        Value::Array(items) => Value::Array(items.iter().map(canonicalize).collect()),
        _ => value.clone(),
    }
}

pub fn canonical_bytes(value: &Value) -> Result<Vec<u8>, String> {
    serde_json::to_vec(&canonicalize(value))
        .map_err(|error| format!("无法生成 canonical JSON：{error}"))
}

pub fn canonical_sha256(value: &Value) -> Result<String, String> {
    let mut hasher = Sha256::new();
    hasher.update(canonical_bytes(value)?);
    Ok(format!("{:x}", hasher.finalize()))
}

fn valid_app_id(value: &str) -> bool {
    if value.is_empty() || value.len() > 128 || !value.is_ascii() {
        return false;
    }
    let mut segment_start = true;
    for byte in value.bytes() {
        if segment_start {
            if !byte.is_ascii_lowercase() && !byte.is_ascii_digit() {
                return false;
            }
            segment_start = false;
        } else if byte == b'.' || byte == b'-' {
            segment_start = true;
        } else if !byte.is_ascii_lowercase() && !byte.is_ascii_digit() {
            return false;
        }
    }
    !segment_start && value.as_bytes()[0].is_ascii_lowercase()
}

fn valid_semver(value: &str) -> bool {
    let parts = value.split('.').collect::<Vec<_>>();
    parts.len() == 3
        && parts.iter().all(|part| {
            !part.is_empty()
                && part.bytes().all(|byte| byte.is_ascii_digit())
                && (part == &"0" || !part.starts_with('0'))
        })
}

fn cargo_package_name(package_intent: &Value) -> Result<String, String> {
    let app_id = package_intent["app_id"]
        .as_str()
        .ok_or_else(|| "package_intent.app_id 缺失。".to_string())?;
    if !valid_app_id(app_id) {
        return Err("package_intent.app_id 不是有效的 VibApp 标识。".to_string());
    }
    let candidate = app_id.replace('.', "_");
    if candidate.len() <= 64 {
        return Ok(candidate);
    }
    let suffix = format!("{:x}", Sha256::digest(app_id.as_bytes()));
    Ok(format!("{}-{}", &candidate[..51], &suffix[..12]))
}

fn cargo_manifest_bytes(package_intent: &Value) -> Result<Vec<u8>, String> {
    let app_id = package_intent["app_id"]
        .as_str()
        .ok_or_else(|| "package_intent.app_id 缺失。".to_string())?;
    let version = package_intent["version"]
        .as_str()
        .ok_or_else(|| "package_intent.version 缺失。".to_string())?;
    if !valid_semver(version) {
        return Err("package_intent.version 不是简单语义版本。".to_string());
    }
    let name = cargo_package_name(package_intent)?;
    Ok(format!(
        "# Generated by {CARGO_SCAFFOLD_POLICY_VERSION}.\n\
# Source: consent-bound package_intent.app_id={app_id} and package_intent.version={version}.\n\
# Provider edits are rejected by exact post-execution byte and digest validation.\n\
[package]\n\
name = \"{name}\"\n\
version = \"{version}\"\n\
edition = \"2024\"\n\
publish = false\n\
autobins = false\n\
autoexamples = false\n\
autotests = false\n\
autobenches = false\n\
\n\
[lib]\n\
crate-type = [\"cdylib\"]\n\
\n\
[dependencies]\n\
wit-bindgen = {{ version = \"=0.60.0\", default-features = false, features = [\"bitflags\", \"macro-string\", \"macros\", \"realloc\"] }}\n"
    )
    .into_bytes())
}

fn cargo_scaffold(package_intent: &Value) -> Result<Value, String> {
    let bytes = cargo_manifest_bytes(package_intent)?;
    let package_version = package_intent["version"]
        .as_str()
        .ok_or_else(|| "package_intent.version 缺失。".to_string())?;
    Ok(json!({
        "policy_version": CARGO_SCAFFOLD_POLICY_VERSION,
        "source": "task.package_intent.app_id+version",
        "path": "source/Cargo.toml",
        "package_name": cargo_package_name(package_intent)?,
        "package_version": package_version,
        "sha256": format!("{:x}", Sha256::digest(&bytes))
    }))
}

pub fn initial_state(route: &str) -> Value {
    let mut blockers = vec![
        "need-incomplete",
        "package-intent-unconfirmed",
        "consent-required",
        "external-opt-in-required",
        "cloud-worker-fresh-reaccept-required",
    ];
    if route == "recommendation" {
        blockers.insert(0, "existing-app-recommendation-awaiting-user-choice");
    }
    json!({
        "enabled": false,
        "state": "disabled",
        "blockers": blockers,
        "worker_contract": {
            "schema_version": TASK_SCHEMA_VERSION,
            "schema_snapshot_sha256": TASK_SCHEMA_SNAPSHOT_SHA256,
            "policy_version": POLICY_VERSION,
            "state": "available-read-only-not-invoked"
        },
        "required_conditions": {
            "need_spec_complete": false,
            "need_spec_digest_bound": false,
            "package_intent_confirmed": false,
            "remote_processing_consent": false,
            "consent_decision": "not-requested",
            "single_use_consent_issued": false,
            "consent_job_bound": false,
            "consent_payload_digest_bound": false,
            "provider_execution_identity_bound": false,
            "external_cost_acknowledged": false,
            "cloud_worker_fresh_reaccept": false
        },
        "task_preparation": {
            "eligible": false,
            "schema_preview_available": false,
            "schema_preview": null,
            "task_created": false,
            "task": null
        },
        "external_request_made": false,
        "codeagent_task_created": false
    })
}

pub struct CompletePreview<'a> {
    pub provider: &'a str,
    pub model: &'a str,
    pub provider_execution_identity: ProviderExecutionIdentityPreview<'a>,
    pub execution_attempt: ExecutionAttemptPreview<'a>,
    pub need_spec: &'a Value,
    pub need_spec_digest: &'a str,
    pub package_intent: &'a Value,
    pub app_kind: &'a str,
    pub wit_world: &'a str,
    pub profiles: &'a [String],
    pub required_imports: &'a [String],
    pub required_capabilities: &'a [String],
    pub issued_at_utc: &'a str,
    pub expires_at_utc: &'a str,
    pub remote_processing_consent: bool,
    pub public_publication_consent: bool,
    pub existing_app_rejected: bool,
}

pub struct ProviderExecutionIdentityPreview<'a> {
    pub endpoint_kind: &'a str,
    pub canonical_endpoint: &'a str,
    pub adapter_id: &'a str,
    pub adapter_version: &'a str,
    pub adapter_sha256: &'a str,
    pub runtime_package: &'a str,
    pub runtime_version: &'a str,
    pub runtime_executable_sha256: &'a str,
    pub non_secret_config_sha256: &'a str,
}

pub struct ExecutionAttemptPreview<'a> {
    pub attempt_id: &'a str,
    pub ordinal: u32,
}

fn valid_sha256(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn valid_identity_text(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 128
        && value.trim() == value
        && !value.chars().any(char::is_control)
}

fn valid_attempt_id(value: &str, ordinal: u32) -> bool {
    if !(1..=9999).contains(&ordinal) || value.len() != 29 {
        return false;
    }
    let Some((prefix, suffix)) = value.rsplit_once('-') else {
        return false;
    };
    prefix == format!("attempt-{ordinal:04}")
        && suffix.len() == 16
        && suffix
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn valid_canonical_https_endpoint(value: &str) -> bool {
    if !value.is_ascii()
        || value.len() > 512
        || !value.starts_with("https://")
        || value.contains('?')
        || value.contains('#')
        || value.contains('\\')
    {
        return false;
    }
    let remainder = &value["https://".len()..];
    let (authority, path) = match remainder.split_once('/') {
        Some((authority, path)) => (authority, Some(path)),
        None => (remainder, None),
    };
    if authority.is_empty() || authority.contains('@') {
        return false;
    }
    let (host, port) = match authority.rsplit_once(':') {
        Some((host, port)) => {
            if host.contains(':') || port.is_empty() || (port.len() > 1 && port.starts_with('0')) {
                return false;
            }
            let Ok(port) = port.parse::<u16>() else {
                return false;
            };
            if port == 0 || port == 443 {
                return false;
            }
            (host, Some(port))
        }
        None => (authority, None),
    };
    if (port.is_none() && host.contains(':'))
        || host.is_empty()
        || host.ends_with('.')
        || host.bytes().any(|byte| byte.is_ascii_uppercase())
        || host.split('.').any(|label| {
            label.is_empty()
                || label.len() > 63
                || !label.as_bytes()[0].is_ascii_alphanumeric()
                || !label.as_bytes()[label.len() - 1].is_ascii_alphanumeric()
                || label
                    .bytes()
                    .any(|byte| !byte.is_ascii_alphanumeric() && byte != b'-')
        })
    {
        return false;
    }
    let Some(path) = path else {
        return true;
    };
    if path.is_empty()
        || path.ends_with('/')
        || path
            .split('/')
            .any(|segment| segment.is_empty() || matches!(segment, "." | ".."))
    {
        return false;
    }
    let bytes = path.as_bytes();
    let mut index = 0;
    while index < bytes.len() {
        let byte = bytes[index];
        if byte == b'%' {
            if index + 2 >= bytes.len()
                || !matches!(bytes[index + 1], b'0'..=b'9' | b'A'..=b'F')
                || !matches!(bytes[index + 2], b'0'..=b'9' | b'A'..=b'F')
            {
                return false;
            }
            index += 3;
            continue;
        }
        if !(byte.is_ascii_alphanumeric()
            || matches!(
                byte,
                b'-' | b'.'
                    | b'_'
                    | b'~'
                    | b'!'
                    | b'$'
                    | b'&'
                    | b'\''
                    | b'('
                    | b')'
                    | b'*'
                    | b'+'
                    | b','
                    | b';'
                    | b'='
                    | b':'
                    | b'@'
                    | b'/'
            ))
        {
            return false;
        }
        index += 1;
    }
    true
}

fn provider_execution_identity(
    provider: &str,
    input: ProviderExecutionIdentityPreview<'_>,
) -> Result<Value, String> {
    let endpoint_allowed = match input.endpoint_kind {
        "https" => valid_canonical_https_endpoint(input.canonical_endpoint),
        "fixed-lan-http" => provider == "opencode"
            && input.canonical_endpoint == "http://192.168.199.170:8081/v1/chat/completions",
        "provider-managed" => {
            input.canonical_endpoint == "provider-managed"
                && matches!(
                    provider,
                    "openai-codex" | "anthropic-claude-code" | "google-gemini-cli"
                )
        }
        _ => false,
    };
    if !endpoint_allowed {
        return Err("CodeAgent endpoint identity 无效或未显式规范化。".to_string());
    }
    for (value, name) in [
        (input.adapter_id, "adapter_id"),
        (input.adapter_version, "adapter_version"),
        (input.runtime_package, "runtime_package"),
        (input.runtime_version, "runtime_version"),
    ] {
        if !valid_identity_text(value) {
            return Err(format!(
                "CodeAgent provider execution identity 的 {name} 无效。"
            ));
        }
    }
    for (value, name) in [
        (input.adapter_sha256, "adapter_sha256"),
        (input.non_secret_config_sha256, "non_secret_config_sha256"),
    ] {
        if !valid_sha256(value) {
            return Err(format!(
                "CodeAgent provider execution identity 的 {name} 无效。"
            ));
        }
    }
    if !valid_sha256(input.runtime_executable_sha256) {
        return Err("CodeAgent runtime executable digest 无效。".to_string());
    }
    let endpoint_body = json!({
        "kind": input.endpoint_kind,
        "canonical_endpoint": input.canonical_endpoint,
    });
    let endpoint = json!({
        "kind": input.endpoint_kind,
        "canonical_endpoint": input.canonical_endpoint,
        "endpoint_sha256": canonical_sha256(&endpoint_body)?,
    });
    let runtime = json!({
        "adapter_id": input.adapter_id,
        "adapter_version": input.adapter_version,
        "adapter_sha256": input.adapter_sha256,
        "package_id": input.runtime_package,
        "package_version": input.runtime_version,
        "executable_sha256": input.runtime_executable_sha256,
    });
    let identity_body = json!({
        "schema_version": "vibapp.provider-execution-identity.experimental-v1",
        "endpoint": endpoint,
        "runtime": runtime,
        "non_secret_config_sha256": input.non_secret_config_sha256,
    });
    let mut identity = identity_body
        .as_object()
        .cloned()
        .ok_or_else(|| "无法构造 CodeAgent provider execution identity。".to_string())?;
    identity.insert(
        "identity_sha256".to_string(),
        Value::String(canonical_sha256(&identity_body)?),
    );
    Ok(Value::Object(identity))
}

fn frozen_general_instructions(provider: &str) -> Result<String, String> {
    // Read the existing literal from its single source, never evaluate Python.
    // Both historical pins must still match before a new consent can be minted.
    let codex = CLOUD_AGENT_POLICY_SOURCE
        .split_once("PROVIDER_INSTRUCTIONS = \"\"\"")
        .and_then(|(_, tail)| tail.split_once("\"\"\""))
        .map(|(text, _)| text)
        .ok_or_else(|| "CodeAgent 冻结指令正文不可用。".to_string())?;
    if format!("{:x}", Sha256::digest(codex.as_bytes())) != CODEX_INSTRUCTIONS_DIGEST_SHA256 {
        return Err("CodeAgent 冻结指令摘要不匹配。".to_string());
    }
    let other = codex.replace("with the built-in apply_patch editing tool", "with the provider's reviewed file-editing tool")
        .replace("Use apply_patch for source edits.", "Use only the provider's reviewed file-editing tools for source edits.");
    if format!("{:x}", Sha256::digest(other.as_bytes())) != OTHER_PROVIDER_INSTRUCTIONS_DIGEST_SHA256 {
        return Err("CodeAgent 通用冻结指令摘要不匹配。".to_string());
    }
    match provider {
        "openai-codex" => Ok(codex.to_string()),
        "opencode" | "anthropic-claude-code" | "google-gemini-cli" => Ok(other),
        _ => Err("CodeAgent provider 不受支持。".to_string()),
    }
}

fn support_instructions(template: &str) -> String {
    let support_digest = format!("{:x}", Sha256::digest(OPENCODE_UI_SUPPORT));
    let guide_digest = format!("{:x}", Sha256::digest(OPENCODE_UI_GUIDE));
    format!("{template}\nUI support SHA256: {support_digest}\nUI guide SHA256: {guide_digest}\n")
}

fn with_ui_ux_skill_digest(base: &str) -> String {
    let skill_digest = format!("{:x}", Sha256::digest(UI_UX_SKILL));
    let instructions = format!(
        "{base}\nTrusted application-experience guidance:\n\
         Before authoring, read contracts/vibapp-ui-ux.md completely and apply its relevant guidance. \
         This immutable document is passive task input, not permission to invoke skills, plugins, hooks or external tools. \
         Do not edit, remove, chmod or recreate it. For service-only apps apply lifecycle and capability honesty without inventing a GUI; \
         it does not supply UI-only Rust support for other worlds.\n\
         VibApp UI/UX skill SHA256: {skill_digest}\n"
    );
    format!("{:x}", Sha256::digest(instructions.as_bytes()))
}

fn instructions_digest(provider: &str) -> Result<String, String> {
    // Provider-only preview has no world yet, matching Python's task=None.
    let base = if provider == "opencode" {
        support_instructions(OPENCODE_INSTRUCTIONS)
    } else {
        frozen_general_instructions(provider)?
    };
    Ok(with_ui_ux_skill_digest(&base))
}

fn uses_codex_ui_support(provider: &str, wit_world: &str, runtime_package: &str) -> bool {
    provider == "openai-codex"
        && wit_world == "ui-only-reference"
        && runtime_package == "openai-codex-cli-docker"
}

fn task_instructions_digest(
    provider: &str,
    wit_world: &str,
    runtime_package: &str,
) -> Result<String, String> {
    let base = if uses_codex_ui_support(provider, wit_world, runtime_package) {
        support_instructions(CODEX_UI_INSTRUCTIONS)
    } else if provider == "opencode" && wit_world == "ui-only-reference" {
        support_instructions(OPENCODE_INSTRUCTIONS)
    } else {
        frozen_general_instructions(provider)?
    };
    Ok(with_ui_ux_skill_digest(&base))
}

pub fn completed_state(input: CompletePreview<'_>) -> Result<Value, String> {
    if !valid_sha256(input.need_spec_digest)
        || canonical_sha256(input.need_spec)? != input.need_spec_digest
    {
        return Err("NeedSpec digest 必须匹配 canonical NeedSpec payload。".to_string());
    }
    let ui_support = (input.provider == "opencode" && input.wit_world == "ui-only-reference") || uses_codex_ui_support(
        input.provider,
        input.wit_world,
        input.provider_execution_identity.runtime_package,
    );
    let instructions_digest = task_instructions_digest(
        input.provider,
        input.wit_world,
        input.provider_execution_identity.runtime_package,
    )?;
    let cargo_scaffold = cargo_scaffold(input.package_intent)?;
    if !valid_attempt_id(
        input.execution_attempt.attempt_id,
        input.execution_attempt.ordinal,
    ) {
        return Err("CodeAgent execution attempt 绑定无效。".to_string());
    }
    let execution_attempt = json!({
        "attempt_id": input.execution_attempt.attempt_id,
        "ordinal": input.execution_attempt.ordinal,
    });
    let provider_execution_identity =
        provider_execution_identity(input.provider, input.provider_execution_identity)?;
    if input.model.is_empty()
        || input.model.trim() != input.model
        || input.model.chars().count() > 256
        || input.model.starts_with('-')
        || input.model.chars().any(char::is_control)
    {
        return Err("CodeAgent model 绑定无效。".to_string());
    }
    let target = json!({
        "contract": "vibapp:experimental-v0@0.0.1",
        "wasi": "0.2",
        "rust_target": "wasm32-wasip2",
        "wit_world": input.wit_world,
        "app_kind": input.app_kind,
        "profiles": input.profiles,
        "required_imports": input.required_imports,
        "required_capabilities": input.required_capabilities
    });
    let limits = json!({
        "wall_time_seconds": 1800,
        "cpu_seconds": 600,
        "memory_bytes": 2147483648_u64,
        "pids": 64,
        "workspace_bytes": 67108864,
        "stdout_bytes": 1048576,
        "stderr_bytes": 262144,
        "source_bytes": 8388608,
        "source_files": 128
    });
    let job_seed = json!({
        "need_spec_digest_sha256": input.need_spec_digest,
        "package_intent": input.package_intent,
        "target": target,
        "provider": input.provider,
        "model": input.model,
        "provider_execution_identity": provider_execution_identity,
    });
    let job_seed_digest = canonical_sha256(&job_seed)?;
    let job_id = format!("job-cloud-{}", &job_seed_digest[..24]);
    let provider_request = json!({
        "schema_version": PROVIDER_REQUEST_VERSION,
        "policy_version": POLICY_VERSION,
        "job_id": job_id,
        "provider": input.provider,
        "model": input.model,
        "provider_execution_identity": provider_execution_identity,
        "need_spec_current_revision": input.need_spec["revision"],
        "need_spec": input.need_spec,
        "package_intent": input.package_intent,
        "target": target,
        "limits": limits,
        "contract_digest_sha256": CONTRACT_DIGEST_SHA256,
        "instructions_digest_sha256": instructions_digest,
        "cargo_scaffold": cargo_scaffold
    });
    let immutable_task_digest = canonical_sha256(&provider_request)?;
    let consent_seed = json!({
        "immutable_task_digest_sha256": immutable_task_digest,
        "execution_attempt": execution_attempt,
    });
    let consent_seed_digest = canonical_sha256(&consent_seed)?;
    let consent_id = format!("consent-cloud-{}", &consent_seed_digest[..24]);
    let consent_binding = json!({
        "consent_id": consent_id,
        "consent_type": "remote-processing",
        "decision": if input.remote_processing_consent { "granted" } else { "not-requested" },
        "subject": input.need_spec["owner"],
        "job_id": job_id,
        "attempt_id": input.execution_attempt.attempt_id,
        "provider": input.provider,
        "model": input.model,
        "provider_execution_identity_sha256": provider_execution_identity["identity_sha256"],
        "payload_digest_sha256": immutable_task_digest,
        "uploaded_data_classes": DISCLOSED_DATA_CLASSES,
        "single_use": input.remote_processing_consent,
        "issued_at_utc": input.issued_at_utc,
        "expires_at_utc": input.expires_at_utc,
        "policy_version": POLICY_VERSION,
        "contract_digest_sha256": CONTRACT_DIGEST_SHA256,
        "instructions_digest_sha256": instructions_digest
    });
    let data_leaving_device = json!({
        "summary": if ui_support {
            "仅上传完整 NeedSpec、package intent、目标合同、执行上限、已选 provider/model、不含秘密的 endpoint/runtime identity、生成策略、权威合同，以及摘要绑定的通用平台 Rust 支持库、指南与默认 UI/UX 技能文档；不上传用户或应用源码、本地用户文件、凭据、诊断日志或公开发布授权。"
        } else {
            "仅上传完整 NeedSpec、package intent、目标合同、执行上限、已选 provider/model、不含秘密的 endpoint/runtime identity、生成策略、权威合同与摘要绑定的默认 UI/UX 技能文档；技能不授予额外权限或虚构界面支持，不包含应用源代码、本地用户文件、凭据、诊断日志或公开发布授权。"
        },
        "classes": DISCLOSED_DATA_CLASSES,
        "fields": [
            "goal",
            "requirements-and-acceptance-examples",
            "negative-constraints",
            "platforms-and-profiles",
            "permission-ceiling",
            "package-intent",
            "codeagent-provider-and-model",
            "provider-endpoint-runtime-and-non-secret-config-digests",
            "target-contract-and-imports",
            "consent-bound-ui-ux-skill"
        ],
        "excludes": if ui_support {
            json!(["user-and-app-source", "local-user-files", "credentials", "diagnostic-log", "public-publication-consent"])
        } else {
            json!(["source", "local-files", "credentials", "diagnostic-log", "public-publication-consent"])
        },
        "need_spec_digest_sha256": input.need_spec_digest,
        "immutable_task_digest_sha256": immutable_task_digest,
        "provider": input.provider,
        "model": input.model,
        "provider_execution_identity_sha256": provider_execution_identity["identity_sha256"],
        "execution_attempt": execution_attempt,
    });

    let can_preview = input.remote_processing_consent && input.existing_app_rejected;
    let task_preview = if can_preview {
        Some(json!({
            "schema_version": TASK_SCHEMA_VERSION,
            "document_type": "cloud-codeagent-task",
            "job_id": job_id,
            "execution_attempt": execution_attempt,
            "need_spec_complete": true,
            "need_spec_current_revision": input.need_spec["revision"],
            "need_spec_digest_sha256": input.need_spec_digest,
            "immutable_task_digest_sha256": immutable_task_digest,
            "need_spec": input.need_spec,
            "package_intent": input.package_intent,
            "remote_processing_consent": true,
            "consent": consent_binding,
            "provider": input.provider,
            "model": input.model,
            "provider_execution_identity": provider_execution_identity,
            "target": target,
            "limits": limits
        }))
    } else {
        None
    };

    let mut blockers = vec![
        "external-opt-in-required",
        "cloud-worker-fresh-reaccept-required",
    ];
    if !input.remote_processing_consent {
        blockers.insert(0, "consent-required");
    }
    if !input.existing_app_rejected {
        blockers.insert(0, "existing-app-recommendation-awaiting-user-choice");
    }
    Ok(json!({
        "enabled": false,
        "state": "schema-preview-only",
        "blockers": blockers,
        "worker_contract": {
            "schema_version": TASK_SCHEMA_VERSION,
            "schema_snapshot_sha256": TASK_SCHEMA_SNAPSHOT_SHA256,
            "policy_version": POLICY_VERSION,
            "state": "available-read-only-not-invoked"
        },
        "required_conditions": {
            "need_spec_complete": true,
            "need_spec_digest_bound": true,
            "package_intent_confirmed": true,
            "remote_processing_consent": input.remote_processing_consent,
            "consent_decision": if input.remote_processing_consent { "granted" } else { "not-requested" },
            "single_use_consent_issued": input.remote_processing_consent,
            "consent_job_bound": input.remote_processing_consent,
            "consent_payload_digest_bound": input.remote_processing_consent,
            "provider_execution_identity_bound": input.remote_processing_consent,
            "external_cost_acknowledged": false,
            "cloud_worker_fresh_reaccept": false
        },
        "data_leaving_device": data_leaving_device,
        "consent_binding": consent_binding,
        "publication": {
            "consent": input.public_publication_consent,
            "performed": false,
            "independent_from_remote_processing": true
        },
        "task_preparation": {
            "eligible": false,
            "schema_preview_available": task_preview.is_some(),
            "schema_preview": task_preview,
            "task_created": false,
            "task": null
        },
        "external_request_made": false,
        "codeagent_task_created": false
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn synthetic_provider_identity(provider: &str) -> ProviderExecutionIdentityPreview<'static> {
        let (endpoint_kind, canonical_endpoint, package) = if provider == "opencode" {
            ("https", "https://api.example.com/v1", "opencode-ai")
        } else {
            ("provider-managed", "provider-managed", "provider-cli")
        };
        ProviderExecutionIdentityPreview {
            endpoint_kind,
            canonical_endpoint,
            adapter_id: "local-codeagent-adapter",
            adapter_version: "experimental-v1",
            adapter_sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            runtime_package: package,
            runtime_version: "fixture-1.0.0",
            runtime_executable_sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            non_secret_config_sha256: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        }
    }

    fn opencode_identity_with_endpoint(
        canonical_endpoint: &'static str,
    ) -> ProviderExecutionIdentityPreview<'static> {
        ProviderExecutionIdentityPreview {
            endpoint_kind: "https",
            canonical_endpoint,
            adapter_id: "local-codeagent-adapter",
            adapter_version: "experimental-v1",
            adapter_sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            runtime_package: "opencode-ai",
            runtime_version: "fixture-1.0.0",
            runtime_executable_sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            non_secret_config_sha256: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        }
    }

    fn first_attempt() -> ExecutionAttemptPreview<'static> {
        ExecutionAttemptPreview {
            attempt_id: "attempt-0001-0123456789abcdef",
            ordinal: 1,
        }
    }

    #[test]
    fn consent_digest_matches_the_exact_codeagent_instructions() {
        let source = include_str!("../../../cloud-agent/cloud_agent.py");
        let marker = "PROVIDER_INSTRUCTIONS = \"\"\"";
        let instructions = source
            .split_once(marker)
            .expect("cloud agent must declare provider instructions")
            .1
            .split_once("\"\"\"")
            .expect("provider instructions must have a closing delimiter")
            .0;
        assert_eq!(
            format!("{:x}", Sha256::digest(instructions.as_bytes())),
            CODEX_INSTRUCTIONS_DIGEST_SHA256,
            "Desktop consent must bind the complete CodeAgent instruction text"
        );
        let other = instructions
            .replace(
                "with the built-in apply_patch editing tool",
                "with the provider's reviewed file-editing tool",
            )
            .replace(
                "Use apply_patch for source edits.",
                "Use only the provider's reviewed file-editing tools for source edits.",
            );
        assert_eq!(
            format!("{:x}", Sha256::digest(other.as_bytes())),
            OTHER_PROVIDER_INSTRUCTIONS_DIGEST_SHA256,
            "Desktop consent must bind the generic provider instruction text"
        );
    }

    #[test]
    fn every_supported_provider_binds_its_exact_instruction_digest() {
        let need = json!({
            "revision": 2,
            "owner": {"principal_id": "desktop.local.user", "principal_kind": "user"}
        });
        let need_digest = canonical_sha256(&need).unwrap();
        let package = json!({"app_id": "ai.vibapp.test", "version": "0.1.0"});
        let profiles = vec!["desktop".to_string()];
        let imports = vec![
            "vibapp:experimental-v0/clock@0.0.1".to_string(),
            "vibapp:experimental-v0/kv@0.0.1".to_string(),
            "vibapp:experimental-v0/log@0.0.1".to_string(),
            "vibapp:experimental-v0/host-info@0.0.1".to_string(),
            "vibapp:experimental-v0/settings@0.0.1".to_string(),
        ];
        for provider in [
            "openai-codex",
            "anthropic-claude-code",
            "opencode",
            "google-gemini-cli",
        ] {
            let state = completed_state(CompletePreview {
                provider,
                model: "provider-model",
                provider_execution_identity: synthetic_provider_identity(provider),
                execution_attempt: first_attempt(),
                need_spec: &need,
                need_spec_digest: &need_digest,
                package_intent: &package,
                app_kind: "ui",
                wit_world: "ui-only-reference",
                profiles: &profiles,
                required_imports: &imports,
                required_capabilities: &imports,
                issued_at_utc: "2026-08-24T04:00:00Z",
                expires_at_utc: "2026-08-24T04:15:00Z",
                remote_processing_consent: true,
                public_publication_consent: false,
                existing_app_rejected: true,
            })
            .unwrap();
            let task = &state["task_preparation"]["schema_preview"];
            assert_eq!(task["provider"], provider);
            assert_eq!(
                task["consent"]["instructions_digest_sha256"],
                instructions_digest(provider).unwrap()
            );
        }
    }

    #[test]
    fn opencode_instruction_digest_matches_actual_python_without_provider_call() {
        // Import only the source policy module. No CLI execution, model request,
        // credentials, consent or bytecode writes are involved in this parity test.
        let cloud_agent = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../cloud-agent/cloud_agent.py");
        let python = std::process::Command::new("python3")
            .args(["-I", "-B", "-c"])
            .arg(
                "import importlib.util,sys;\
                 spec=importlib.util.spec_from_file_location('vibapp_instruction_parity',sys.argv[1]);\
                 module=importlib.util.module_from_spec(spec);\
                 sys.modules[spec.name]=module;spec.loader.exec_module(module);\
                 print(module.provider_instructions_digest('opencode'))",
            )
            .arg(cloud_agent)
            .output()
            .expect("Python is required for the CloudAgent instruction parity check");
        assert!(python.status.success(), "CloudAgent instruction digest observation failed");
        assert_eq!(
            instructions_digest("opencode").unwrap(),
            String::from_utf8(python.stdout).unwrap().trim(),
            "Rust consent must match Python's complete OpenCode trusted-input digest"
        );
        assert_ne!(instructions_digest("openai-codex").unwrap(), CODEX_INSTRUCTIONS_DIGEST_SHA256);
        for provider in ["anthropic-claude-code", "google-gemini-cli"] {
            assert_ne!(instructions_digest(provider).unwrap(), OTHER_PROVIDER_INSTRUCTIONS_DIGEST_SHA256);
        }
    }

    #[test]
    fn codex_support_is_limited_to_docker_ui_tasks() {
        let supported = task_instructions_digest(
            "openai-codex", "ui-only-reference", "openai-codex-cli-docker",
        ).unwrap();
        assert_ne!(supported, CODEX_INSTRUCTIONS_DIGEST_SHA256);
        for (world, package) in [
            ("ui-only-reference", "provider-cli"),
            ("service-only-reference", "openai-codex-cli-docker"),
            ("hybrid-reference", "openai-codex-cli-docker"),
        ] {
            assert_eq!(
                task_instructions_digest("openai-codex", world, package).unwrap(),
                instructions_digest("openai-codex").unwrap(),
            );
        }
        for provider in ["opencode", "anthropic-claude-code", "google-gemini-cli"] {
            assert_eq!(
                task_instructions_digest(provider, "ui-only-reference", "openai-codex-cli-docker").unwrap(),
                instructions_digest(provider).unwrap(),
            );
        }
    }

    #[test]
    fn every_fresh_provider_world_and_provider_only_preview_match_python_skill_policy() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let mut requests = Vec::new();
        let mut expected = Vec::new();
        for provider in ["openai-codex", "opencode", "anthropic-claude-code", "google-gemini-cli"] {
            requests.push(json!({"provider": provider, "task": null}));
            expected.push(instructions_digest(provider).unwrap());
            for world in ["ui-only-reference", "hybrid-reference", "service-only-reference"] {
                for runtime in ["provider-cli", "openai-codex-cli-docker"] {
                    requests.push(json!({"provider": provider, "task": {
                        "schema_version": TASK_SCHEMA_VERSION,
                        "provider": provider,
                        "target": {"wit_world": world},
                        "provider_execution_identity": {"runtime": {"package_id": runtime}}
                    }}));
                    expected.push(task_instructions_digest(provider, world, runtime).unwrap());
                }
            }
        }
        let cloud_agent = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../cloud-agent/cloud_agent.py");
        let mut python = Command::new("python3").args(["-I", "-B", "-c"])
            .arg("import importlib.util,json,sys;\
                  spec=importlib.util.spec_from_file_location('vibapp_skill_matrix',sys.argv[1]);\
                  module=importlib.util.module_from_spec(spec);\
                  sys.modules[spec.name]=module;spec.loader.exec_module(module);\
                  print(json.dumps([module.provider_instructions_digest(row['provider'],row['task']) for row in json.load(sys.stdin)]))")
            .arg(cloud_agent).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped())
            .spawn().expect("Python is required for actual policy parity");
        python.stdin.take().unwrap().write_all(&canonical_bytes(&json!(requests)).unwrap()).unwrap();
        let result = python.wait_with_output().unwrap();
        assert!(result.status.success(), "{}", String::from_utf8_lossy(&result.stderr));
        let actual: Vec<String> = serde_json::from_slice(&result.stdout).unwrap();
        assert_eq!(actual, expected, "Every fresh task binds exact skill and matching world policy");
    }

    #[test]
    fn docker_codex_ui_consent_and_request_match_actual_python() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let fixture: Value = serde_json::from_str(include_str!(
            "../../../cloud-agent/fixtures/valid-task.json"
        )).unwrap();
        let need = &fixture["need_spec"];
        let need_digest = canonical_sha256(need).unwrap();
        let target = &fixture["target"];
        let strings = |name: &str| -> Vec<String> {
            target[name].as_array().unwrap().iter()
                .map(|value| value.as_str().unwrap().to_string()).collect()
        };
        let mut identity = synthetic_provider_identity("openai-codex");
        identity.runtime_package = "openai-codex-cli-docker";
        let state = completed_state(CompletePreview {
            provider: "openai-codex",
            model: "fixture-model",
            provider_execution_identity: identity,
            execution_attempt: first_attempt(),
            need_spec: need,
            need_spec_digest: &need_digest,
            package_intent: &fixture["package_intent"],
            app_kind: "ui",
            wit_world: "ui-only-reference",
            profiles: &strings("profiles"),
            required_imports: &strings("required_imports"),
            required_capabilities: &strings("required_capabilities"),
            issued_at_utc: "2026-08-24T04:00:00Z",
            expires_at_utc: "2026-08-24T04:15:00Z",
            remote_processing_consent: true,
            public_publication_consent: false,
            existing_app_rejected: true,
        }).unwrap();
        let task = &state["task_preparation"]["schema_preview"];
        let expected = task_instructions_digest(
            "openai-codex", "ui-only-reference", "openai-codex-cli-docker",
        ).unwrap();
        assert_eq!(task["consent"]["instructions_digest_sha256"], expected);
        assert!(state["data_leaving_device"]["summary"].as_str().unwrap().contains("Rust 支持库"));
        let cloud_agent = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../cloud-agent/cloud_agent.py");
        let mut python = Command::new("python3")
            .args(["-I", "-B", "-c"])
            .arg(
                "import importlib.util,json,sys;\
                 spec=importlib.util.spec_from_file_location('vibapp_codex_ui_parity',sys.argv[1]);\
                 module=importlib.util.module_from_spec(spec);\
                 sys.modules[spec.name]=module;spec.loader.exec_module(module);\
                 task=module.validate_task_schema(json.load(sys.stdin));\
                 module.validate_authorization(task,module.dt.datetime(2026,8,24,4,5,tzinfo=module.dt.timezone.utc));\
                 print(module.provider_instructions_digest(task['provider'],task));\
                 print(module.immutable_task_digest(task,module.CONTRACT_DIGEST_PIN))",
            )
            .arg(cloud_agent)
            .stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped())
            .spawn().expect("Python is required for Codex UI consent parity");
        python.stdin.take().unwrap().write_all(&canonical_bytes(task).unwrap()).unwrap();
        let result = python.wait_with_output().unwrap();
        assert!(result.status.success(), "{}", String::from_utf8_lossy(&result.stderr));
        let stdout = String::from_utf8(result.stdout).unwrap();
        let lines: Vec<_> = stdout.lines().collect();
        assert_eq!(lines, vec![
            expected.as_str(), task["immutable_task_digest_sha256"].as_str().unwrap(),
        ]);
    }

    #[test]
    fn fixed_lan_preview_is_exact_and_opencode_only() {
        for (provider, endpoint, accepted) in [
            ("opencode", "http://192.168.199.170:8081/v1/chat/completions", true),
            ("openai-codex", "http://192.168.199.170:8081/v1/chat/completions", false),
            ("opencode", "http://127.0.0.1:8081/v1/chat/completions", false),
            ("opencode", "http://192.168.199.170:8081/v1/chat/completions/", false),
        ] {
            let mut identity = synthetic_provider_identity("opencode");
            identity.endpoint_kind = "fixed-lan-http";
            identity.canonical_endpoint = endpoint;
            assert_eq!(provider_execution_identity(provider, identity).is_ok(), accepted);
        }
    }

    #[test]
    fn provider_endpoint_preview_requires_explicit_canonical_https_or_allowed_managed() {
        provider_execution_identity(
            "opencode",
            opencode_identity_with_endpoint("https://api.example.com/v1"),
        )
        .unwrap();
        for endpoint in [
            "https://API.example.com/v1",
            "https://api.example.com:443/v1",
            "https://api.example.com:080/v1",
            "https://user@api.example.com/v1",
            "https://api.example.com/v1/",
            "https://api.example.com/v1/../v2",
            "https://api.example.com/a b",
            "https://api.example.com/v1?key=value",
        ] {
            assert!(
                provider_execution_identity("opencode", opencode_identity_with_endpoint(endpoint))
                    .is_err(),
                "non-canonical endpoint must fail: {endpoint}"
            );
        }
        assert!(
            provider_execution_identity("opencode", synthetic_provider_identity("openai-codex"))
                .is_err(),
            "OpenCode cannot use the provider-managed sentinel"
        );
    }

    #[test]
    fn task_schema_snapshot_matches_the_authoritative_schema() {
        let bytes = include_bytes!("../../../cloud-agent/schemas/cloud-codeagent-task.schema.json");
        assert_eq!(
            format!("{:x}", Sha256::digest(bytes)),
            TASK_SCHEMA_SNAPSHOT_SHA256
        );
        let legacy = include_bytes!(
            "../../../cloud-agent/schemas/cloud-codeagent-task.experimental-v2.schema.json"
        );
        assert_eq!(
            format!("{:x}", Sha256::digest(legacy)),
            "2f145a5ae581d301ba95f4bce35c9373eb983ead491dee0988388a55b067694d",
            "the historical v2 schema must remain byte-for-byte immutable"
        );
    }

    #[test]
    fn producer_task_passes_the_authoritative_v3_schema_validator() {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../../cloud-agent/fixtures/valid-task.json"
        ))
        .unwrap();
        let profiles = fixture["target"]["profiles"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        let imports = fixture["target"]["required_imports"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        let capabilities = fixture["target"]["required_capabilities"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        let need_digest = canonical_sha256(&fixture["need_spec"]).unwrap();
        let state = completed_state(CompletePreview {
            provider: "openai-codex",
            model: "gpt-5.6-sol",
            provider_execution_identity: synthetic_provider_identity("openai-codex"),
            execution_attempt: first_attempt(),
            need_spec: &fixture["need_spec"],
            need_spec_digest: &need_digest,
            package_intent: &fixture["package_intent"],
            app_kind: "ui",
            wit_world: "ui-only-reference",
            profiles: &profiles,
            required_imports: &imports,
            required_capabilities: &capabilities,
            issued_at_utc: "2026-08-30T04:00:00Z",
            expires_at_utc: "2026-08-30T05:00:00Z",
            remote_processing_consent: true,
            public_publication_consent: false,
            existing_app_rejected: true,
        })
        .unwrap();
        let task = &state["task_preparation"]["schema_preview"];
        let path = std::env::temp_dir().join(format!(
            "vibapp-cloud-task-v3-{}-{}.json",
            std::process::id(),
            task["immutable_task_digest_sha256"].as_str().unwrap()
        ));
        std::fs::write(&path, serde_json::to_vec(task).unwrap()).unwrap();
        let validator = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../cloud-agent/cloud_agent.py");
        let output = std::process::Command::new("python3")
            .arg(validator)
            .arg("schema-validate")
            .arg(&path)
            .output()
            .unwrap();
        let _ = std::fs::remove_file(&path);
        assert!(
            output.status.success(),
            "producer output must pass authoritative schema validation: {}",
            String::from_utf8_lossy(&output.stdout)
        );
    }

    #[test]
    fn retry_attempt_changes_consent_not_the_immutable_task_or_need_revision() {
        let fixture: Value = serde_json::from_str(include_str!(
            "../../../cloud-agent/fixtures/valid-task.json"
        ))
        .unwrap();
        let profiles = vec!["desktop".to_string()];
        let imports = fixture["target"]["required_imports"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        let capabilities = fixture["target"]["required_capabilities"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .collect::<Vec<_>>();
        let need_digest = canonical_sha256(&fixture["need_spec"]).unwrap();
        let produce = |attempt_id: &'static str, ordinal| {
            completed_state(CompletePreview {
                provider: "openai-codex",
                model: "gpt-5.6-sol",
                provider_execution_identity: synthetic_provider_identity("openai-codex"),
                execution_attempt: ExecutionAttemptPreview {
                    attempt_id,
                    ordinal,
                },
                need_spec: &fixture["need_spec"],
                need_spec_digest: &need_digest,
                package_intent: &fixture["package_intent"],
                app_kind: "ui",
                wit_world: "ui-only-reference",
                profiles: &profiles,
                required_imports: &imports,
                required_capabilities: &capabilities,
                issued_at_utc: "2026-08-30T04:00:00Z",
                expires_at_utc: "2026-08-30T05:00:00Z",
                remote_processing_consent: true,
                public_publication_consent: false,
                existing_app_rejected: true,
            })
            .unwrap()["task_preparation"]["schema_preview"]
                .clone()
        };
        let first = produce("attempt-0001-0123456789abcdef", 1);
        let retry = produce("attempt-0002-fedcba9876543210", 2);
        assert_eq!(
            first["need_spec_current_revision"],
            retry["need_spec_current_revision"]
        );
        assert_eq!(
            first["immutable_task_digest_sha256"],
            retry["immutable_task_digest_sha256"]
        );
        assert_eq!(first["job_id"], retry["job_id"]);
        assert_ne!(
            first["consent"]["consent_id"],
            retry["consent"]["consent_id"]
        );
    }

    #[test]
    fn cargo_scaffold_matches_the_cloud_agent_vector_exactly() {
        let package = json!({
            "app_id": "ai.vibapp.meeting-prep",
            "version": "0.1.0"
        });
        let bytes = cargo_manifest_bytes(&package).unwrap();
        assert_eq!(
            bytes,
            include_bytes!("../../../cloud-agent/fixtures/dry-run/source/Cargo.toml")
        );
        let scaffold = cargo_scaffold(&package).unwrap();
        assert_eq!(scaffold["package_name"], "ai_vibapp_meeting-prep");
        assert_eq!(scaffold["package_version"], "0.1.0");
        assert_eq!(
            scaffold["sha256"],
            "0ca58522ac65ad50df7e1b724a39c2f89e8fe0429ec10d11204539011febfa6e"
        );
    }

    #[test]
    fn long_app_id_has_the_same_bounded_hash_name_policy() {
        let app_id = format!("ai.vibapp.{}", "a".repeat(80));
        let package = json!({"app_id": app_id, "version": "1.2.3"});
        let name = cargo_package_name(&package).unwrap();
        assert_eq!(name.len(), 64);
        assert_eq!(
            name,
            format!(
                "{}-{}",
                package["app_id"].as_str().unwrap().replace('.', "_")[..51].to_string(),
                &format!(
                    "{:x}",
                    Sha256::digest(package["app_id"].as_str().unwrap().as_bytes())
                )[..12]
            )
        );
    }

    #[test]
    fn canonical_digest_ignores_object_insertion_order() {
        let left: Value = serde_json::from_str(r#"{"b":2,"a":{"d":4,"c":3}}"#).unwrap();
        let right: Value = serde_json::from_str(r#"{"a":{"c":3,"d":4},"b":2}"#).unwrap();
        assert_eq!(
            canonical_bytes(&left).unwrap(),
            canonical_bytes(&right).unwrap()
        );
        assert_eq!(
            canonical_sha256(&left).unwrap(),
            canonical_sha256(&right).unwrap()
        );
    }

    #[test]
    fn task_preview_rejects_null_equivalent_and_blank_model_inputs() {
        let need = json!({
            "revision": 2,
            "owner": {"principal_id": "desktop.local.user", "principal_kind": "user"}
        });
        let need_digest = canonical_sha256(&need).unwrap();
        let package = json!({"app_id": "ai.vibapp.test", "version": "0.1.0"});
        let profiles = vec!["desktop".to_string()];
        let imports = vec![
            "vibapp:experimental-v0/clock@0.0.1".to_string(),
            "vibapp:experimental-v0/kv@0.0.1".to_string(),
            "vibapp:experimental-v0/log@0.0.1".to_string(),
            "vibapp:experimental-v0/host-info@0.0.1".to_string(),
            "vibapp:experimental-v0/settings@0.0.1".to_string(),
        ];
        for model in ["", "   ", " gpt-explicit", "gpt-explicit "] {
            let result = completed_state(CompletePreview {
                provider: "openai-codex",
                model,
                provider_execution_identity: synthetic_provider_identity("openai-codex"),
                execution_attempt: first_attempt(),
                need_spec: &need,
                need_spec_digest: &need_digest,
                package_intent: &package,
                app_kind: "ui",
                wit_world: "ui-only-reference",
                profiles: &profiles,
                required_imports: &imports,
                required_capabilities: &imports,
                issued_at_utc: "2026-08-24T04:00:00Z",
                expires_at_utc: "2026-08-24T04:15:00Z",
                remote_processing_consent: true,
                public_publication_consent: false,
                existing_app_rejected: true,
            });
            assert!(result.unwrap_err().contains("model"));
        }
    }

    #[test]
    fn initial_state_never_creates_a_task() {
        for route in ["recommendation", "refinement"] {
            let state = initial_state(route);
            assert_eq!(state["task_preparation"]["task_created"], json!(false));
            assert!(state["task_preparation"]["task"].is_null());
            assert_eq!(state["external_request_made"], json!(false));
        }
    }

    #[test]
    fn complete_state_exposes_schema_preview_but_never_creates_task() {
        let need = json!({
            "revision": 2,
            "owner": {"principal_id": "desktop.local.user", "principal_kind": "user"}
        });
        let need_digest = canonical_sha256(&need).unwrap();
        let package = json!({"app_id": "ai.vibapp.test", "version": "0.1.0"});
        let profiles = vec!["desktop".to_string()];
        let imports = vec![
            "vibapp:experimental-v0/clock@0.0.1".to_string(),
            "vibapp:experimental-v0/kv@0.0.1".to_string(),
            "vibapp:experimental-v0/log@0.0.1".to_string(),
            "vibapp:experimental-v0/host-info@0.0.1".to_string(),
            "vibapp:experimental-v0/settings@0.0.1".to_string(),
        ];
        let state = completed_state(CompletePreview {
            provider: "openai-codex",
            model: "gpt-authorized",
            provider_execution_identity: synthetic_provider_identity("openai-codex"),
            execution_attempt: first_attempt(),
            need_spec: &need,
            need_spec_digest: &need_digest,
            package_intent: &package,
            app_kind: "ui",
            wit_world: "ui-only-reference",
            profiles: &profiles,
            required_imports: &imports,
            required_capabilities: &imports,
            issued_at_utc: "2026-08-24T04:00:00Z",
            expires_at_utc: "2026-08-24T04:15:00Z",
            remote_processing_consent: true,
            public_publication_consent: false,
            existing_app_rejected: true,
        })
        .unwrap();
        assert_eq!(state["task_preparation"]["schema_preview_available"], true);
        assert_eq!(state["task_preparation"]["task_created"], false);
        assert!(state["task_preparation"]["task"].is_null());
        assert_eq!(state["external_request_made"], false);
        assert_eq!(
            state["task_preparation"]["schema_preview"]["consent"]["uploaded_data_classes"],
            json!(DISCLOSED_DATA_CLASSES)
        );
        assert_eq!(
            state["task_preparation"]["schema_preview"]["immutable_task_digest_sha256"],
            state["task_preparation"]["schema_preview"]["consent"]["payload_digest_sha256"]
        );
        assert_eq!(
            state["task_preparation"]["schema_preview"]["model"],
            "gpt-authorized"
        );
        assert_eq!(
            state["task_preparation"]["schema_preview"]["consent"]["model"],
            "gpt-authorized"
        );
        let changed_model = completed_state(CompletePreview {
            provider: "openai-codex",
            model: "gpt-new-setting",
            provider_execution_identity: synthetic_provider_identity("openai-codex"),
            execution_attempt: first_attempt(),
            need_spec: &need,
            need_spec_digest: &need_digest,
            package_intent: &package,
            app_kind: "ui",
            wit_world: "ui-only-reference",
            profiles: &profiles,
            required_imports: &imports,
            required_capabilities: &imports,
            issued_at_utc: "2026-08-24T04:00:00Z",
            expires_at_utc: "2026-08-24T04:15:00Z",
            remote_processing_consent: true,
            public_publication_consent: false,
            existing_app_rejected: true,
        })
        .unwrap();
        assert_ne!(
            state["task_preparation"]["schema_preview"]["immutable_task_digest_sha256"],
            changed_model["task_preparation"]["schema_preview"]["immutable_task_digest_sha256"]
        );
    }

    #[test]
    fn publication_consent_never_grants_remote_processing_or_publishes() {
        let need = json!({
            "revision": 2,
            "owner": {"principal_id": "desktop.local.user", "principal_kind": "user"}
        });
        let need_digest = canonical_sha256(&need).unwrap();
        let package = json!({"app_id": "ai.vibapp.test", "version": "0.1.0"});
        let profiles = vec!["desktop".to_string()];
        let imports = vec![
            "vibapp:experimental-v0/clock@0.0.1".to_string(),
            "vibapp:experimental-v0/kv@0.0.1".to_string(),
            "vibapp:experimental-v0/log@0.0.1".to_string(),
            "vibapp:experimental-v0/host-info@0.0.1".to_string(),
            "vibapp:experimental-v0/settings@0.0.1".to_string(),
        ];
        let state = completed_state(CompletePreview {
            provider: "openai-codex",
            model: "gpt-publication-preview-explicit",
            provider_execution_identity: synthetic_provider_identity("openai-codex"),
            execution_attempt: first_attempt(),
            need_spec: &need,
            need_spec_digest: &need_digest,
            package_intent: &package,
            app_kind: "ui",
            wit_world: "ui-only-reference",
            profiles: &profiles,
            required_imports: &imports,
            required_capabilities: &imports,
            issued_at_utc: "2026-08-24T04:00:00Z",
            expires_at_utc: "2026-08-24T04:15:00Z",
            remote_processing_consent: false,
            public_publication_consent: true,
            existing_app_rejected: true,
        })
        .unwrap();
        assert_eq!(state["publication"]["consent"], true);
        assert_eq!(state["publication"]["performed"], false);
        assert_eq!(
            state["required_conditions"]["remote_processing_consent"],
            false
        );
        assert_eq!(state["task_preparation"]["schema_preview_available"], false);
        assert_eq!(state["task_preparation"]["task_created"], false);
        assert_eq!(state["external_request_made"], false);
    }
}
